### ISSUE TITLE
Failure starting dovecot

### ISSUE THREAD

**Issue by pauldorn** [adaline/dockermail#6] opened 2015-09-01 20:02 UTC
I followed the READMEs and configured everything =.  I believe it is all correct, having rechecked a number of times.
I get this strangeness when I docker-compose up

**********************************************************
 * Restarting IMAP/POP3 mail server dovecot
   ...done.
 * Starting IMAP/POP3 mail server dovecot
Fatal: Dovecot is already running with PID 2828 (read from /var/run/dovecot/master.pid)
   ...fail!
invoke-rc.d: initscript dovecot, action "start" failed.
dpkg: error processing package dovecot-core (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 dovecot-core
E: Sub-process /usr/bin/dpkg returned an error code (1)
Service 'core' failed to build: The command '/bin/sh -c echo "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d &&     apt-get update && apt-get install -y     ssl-cert     postfix     dovecot-imapd &&     apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 100

**Comment by adaline** [comment] 2015-09-01 20:31
Hi Paul,
can you tell me if you are using all the modules, or just a select few?
Perhaps you can provide your `docker-compose.yml` if its different from the example.
Also would it be possible to show the full build log for docker-compose (perhaps in http://pastebin.com/ so its better formatted).

I tried the build on my machine which went fine, so I assume its some kind of config issue or perhaps docker is not as it promises to be! :)
Thanks,
Val

**Comment by pauldorn** [comment] 2015-09-01 20:37
I am using everything just as it exists here, with the addition of the config files.
I will follow up with a full log when I try again in the morning.  End of my day here.

**Comment by minamorl** [comment] 2015-09-02 19:41
Hi,
I just got same issue today. 
This is full of logs when I execute "docker-composer up".
http://pastebin.com/xf4e1T1f

I hope this will help you.
minamorl

**Comment by adaline** [comment] 2015-09-03 11:02
Thanks @minamorl !
I tried to replicate the issue this morning, but could not, the build worked every time.
I have upgraded docker and docker-compose to latest versions, removed and rebuilt all images, but it still works.

To me it looks like dovecot tries to start before the previous command finished exiting. Im looking deeper into this issue, will let you know how it goes.

**Comment by galuszkak** [comment] 2015-10-01 07:56
Hi @adaline  I have exact same issue.

**Comment by adaline** [comment] 2015-10-01 09:17
@pauldorn @minamorl @galuszkak Hello guys,
I have pushed a workaround for the Docker user bug, can you check that it resolves this issue for you please?
I have successfully built an image on my machine, but it may be unaffected by the issue to begin with.

**Comment by galuszkak** [comment] 2015-10-01 09:46
@adaline seems issue still persist...
```
[...]
Running newaliases
 * Stopping Postfix Mail Transport Agent postfix
   ...done.
 * Starting Postfix Mail Transport Agent postfix
   ...done.
Setting up python2.7 (2.7.8-10ubuntu1.1) ...
Setting up python-minimal (2.7.8-1) ...
Setting up python (2.7.8-1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up dovecot-imapd (1:2.2.9-1ubuntu5) ...

Creating config file /etc/dovecot/conf.d/20-imap.conf with new version
Processing triggers for libc-bin (2.19-10ubuntu2.3) ...
Processing triggers for dovecot-core (1:2.2.9-1ubuntu5) ...
 * Restarting IMAP/POP3 mail server dovecot
   ...done.
 * Starting IMAP/POP3 mail server dovecot
Fatal: Dovecot is already running with PID 2830 (read from /var/run/dovecot/master.pid)
   ...fail!
invoke-rc.d: initscript dovecot, action "start" failed.
dpkg: error processing package dovecot-core (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 dovecot-core
```

**Comment by galuszkak** [comment] 2015-10-01 09:47
@adaline sounds is a some bug in dovecot-core. Somehow it first restart and after that is trying to start already started service...

**Comment by adaline** [comment] 2015-10-01 11:12
@galuszkak thanks for the quick feedback dude,
I have updated the dockerfiles to use latest (stable) ubuntu base image with hopes that uses a better dovecot package.
It builds on my machine:
```
Running newaliases
 * Stopping Postfix Mail Transport Agent postfix
   ...done.
 * Starting Postfix Mail Transport Agent postfix
   ...done.
Setting up tcpd (7.6.q-25) ...
Processing triggers for libc-bin (2.21-0ubuntu4) ...
Processing triggers for systemd (219-7ubuntu6) ...
Processing triggers for dovecot-core (1:2.2.9-1ubuntu5) ...
 * Restarting IMAP/POP3 mail server dovecot
   ...done.
 * Starting IMAP/POP3 mail server dovecot
   ...done.
 ---> b032bd9cfc56
Removing intermediate container 6120e0917f40
```

Can you try to build the latest master please, im not sure why the build would work differently on other machines but it does!

**Comment by galuszkak** [comment] 2015-10-01 15:57
@adaline I tried. But unfourtunetly I have still:
```setting mynetworks: 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
setting mailbox_size_limit: 0
setting recipient_delimiter: +
setting inet_interfaces: all
setting inet_protocols: all
/etc/aliases does not exist, creating it.
WARNING: /etc/aliases exists, but does not have a root alias.

Postfix is now set up with a default configuration.  If you need to make 
changes, edit
/etc/postfix/main.cf (and others) as needed.  To view Postfix configuration
values, see postconf(1).

After modifying main.cf, be sure to run '/etc/init.d/postfix reload'.

Running newaliases
 * Stopping Postfix Mail Transport Agent postfix
   ...done.
 * Starting Postfix Mail Transport Agent postfix
   ...done.
Setting up tcpd (7.6.q-25) ...
Processing triggers for libc-bin (2.21-0ubuntu4) ...
Processing triggers for systemd (219-7ubuntu6) ...
Processing triggers for dovecot-core (1:2.2.9-1ubuntu5) ...
 * Restarting IMAP/POP3 mail server dovecot
   ...done.
 * Starting IMAP/POP3 mail server dovecot
Fatal: Dovecot is already running with PID 3129 (read from /var/run/dovecot/master.pid)
   ...fail!
invoke-rc.d: initscript dovecot, action "start" failed.
dpkg: error processing package dovecot-core (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 dovecot-core
E: Sub-process /usr/bin/dpkg returned an error code (1)
Service 'core' failed to build: The command '/bin/sh -c echo "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d &&     apt-get update && apt-get install -y     ssl-cert     postfix     dovecot-imapd &&     apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 100
```

**Comment by minamorl** [comment] 2015-10-04 20:15
Hi, @adaline 
I tested new version on latest version of docker, but still get same error... These issues seems related to dovecot-core installation.

```
Processing triggers for dovecot-core (1:2.2.9-1ubuntu5) ...
 * Restarting IMAP/POP3 mail server dovecot
   ...done.
 * Starting IMAP/POP3 mail server dovecot
Fatal: Dovecot is already running with PID 3126 (read from /var/run/dovecot/master.pid)
   ...fail!
invoke-rc.d: initscript dovecot, action "start" failed.
dpkg: error processing package dovecot-core (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 dovecot-core
E: Sub-process /usr/bin/dpkg returned an error code (1)
Service 'core' failed to build: The command '/bin/sh -c echo "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d &&     apt-get update && apt-get install -y     ssl-cert     postfix     dovecot-imapd &&     apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 100
```

**Comment by adaline** [comment] 2015-10-04 20:22
Hi @galuszkak and @minamorl,
Thanks for the feedback guys, im having a hard time finding the issue as i cant reproduce the error on my machines.
Can you let me know how you run this please, maybe i can replicate it. Which version of Docker are you using? What platform are you on? Are you running docker in a VM? etc
Thanks!

**Comment by galuszkak** [comment] 2015-10-07 11:17
Hi @adaline . This is mine version
```
root@[test]:~# uname -a
Linux ip-172-31-40-139 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
```
root@[test]:~# docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by minamorl** [comment] 2015-10-08 16:04
@adaline Sorry for my late reply. Here's details. My instance is running on DigitalOcean.
```
% uname -a
Linux {ip} 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
% docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
```
After starting container with `docker-compose up` and I get errors.

**Comment by adaline** [comment] 2015-10-29 17:39
Hi @galuszkak and @minamorl,
I have updated my docker to 1.8.3, docker-compose to 1.5.0rc2 and rebuilt the images with Ubuntu 15.10 base image.
Still cant replicate the issue, my kernel is quite a way over yours though:
```
Linux val 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
Perhaps that is the issue, not sure why that would be though.
Can you please try the latest version, thanks!

**Comment by izderadicka** [comment] 2015-11-11 10:53
I have exactly same issue - it goes down to installation of dovecot  ( I put this into separate step)

```
Step 8 : RUN apt-get install dovecot-imapd
 ---> Running in 6d43c5b2d6fc
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  dovecot-imapd
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 126 kB of archives.
After this operation, 1073 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ wily/main dovecot-imapd amd64 1:2.2.18-2ubuntu2 [126 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 126 kB in 1s (84.4 kB/s)
Selecting previously unselected package dovecot-imapd.
(Reading database ... 9608 files and directories currently installed.)
Preparing to unpack .../dovecot-imapd_1%3a2.2.18-2ubuntu2_amd64.deb ...
Unpacking dovecot-imapd (1:2.2.18-2ubuntu2) ...
Processing triggers for dovecot-core (1:2.2.18-2ubuntu2) ...
 * Restarting IMAP/POP3 mail server dovecot
   ...done.
 * Starting IMAP/POP3 mail server dovecot
Fatal: Dovecot is already running with PID 60 (read from /var/run/dovecot/master.pid)
   ...fail!
invoke-rc.d: initscript dovecot, action "start" failed.
dpkg: error processing package dovecot-core (--unpack):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 dovecot-core
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt-get install dovecot-imapd' returned a non-zero code: 100
```

It looks like there some bug in post-install script in this package - question is why it works for you - where is the difference.  ( I'm running docker 1.7.1 locally on ubuntu 14.04)

**Comment by adaline** [comment] 2015-11-11 11:57
@izderadicka 
Hi Ivan,
Yeah its a hard one, I have run these docker images without issues everywhere, which makes me think that this may be a config issue, but so far I have failed to find a proof of this.

Would you be able to test some code for me:
```
RUN dpkg-divert --local --rename --add /sbin/initctl
RUN ln -s /bin/true /sbin/initctl
```
Add this in the Dockerfile before the dovecot install and let me know if it has any impact.
Thank you

**Comment by izderadicka** [comment] 2015-11-11 13:00
Hi Valentin,

finally  I used other build script -  and it actually uses these two 
commands and worked fine -   just  need to change  ln -s -f  - to 
overwrite existing target.

I.

On 11.11.2015 12:57, Valentin Arkhipov wrote:
>
> @izderadicka <https://github.com/izderadicka>
> Hi Ivan,
> Yeah its a hard one, I have run these docker images without issues 
> everywhere, which makes me think that this may be a config issue, but 
> so far I have failed to find a proof of this.
>
> Would you be able to test some code for me:
>
> |RUN dpkg-divert --local --rename --add /sbin/initctl
> RUN ln -s /bin/true /sbin/initctl
> |
>
> Add this in the Dockerfile before the dovecot install and let me know 
> if it has any impact.
> Thank you
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/adaline/dockermail/issues/6#issuecomment-155756230>.
>


# Dovecot & Postfix testbed for Geary
# Ideas taken from https://github.com/sullof/docker-sshd


FROM ubuntu:trusty
MAINTAINER Charles Lindsay <chaz@yorba.org>

ENV http_proxy http://emea-proxy.uk.oracle.com:80

RUN apt-get update
RUN apt-get upgrade

# Allow dovecot install to succeed (see
# https://github.com/dotcloud/docker/issues/1024)
RUN dpkg-divert --local --rename --add /sbin/initctl
RUN ln -s -f /bin/true /sbin/initctl

# Allow postfix to install without interaction.
RUN echo "postfix postfix/mailname string example.com" | debconf-set-selections
RUN echo "postfix postfix/main_mailer_type string 'Internet Site'" | debconf-set-selections

RUN apt-get install -y openssh-server
RUN apt-get install -y dovecot-imapd
RUN apt-get install -y postfix

RUN mkdir /var/run/sshd
ADD dovecot.conf /etc/dovecot/conf.d/99-test.conf
ADD postfix.cf /postfix.cf.test
RUN cat /postfix.cf.test >> /etc/postfix/main.cf && rm /postfix.cf.test

RUN groupadd test
RUN useradd -g test -m -s /bin/bash test
RUN echo "root:root" | chpasswd
RUN echo "test:test" | chpasswd

ADD init.sh /init.sh

CMD ["/init.sh"]

**Comment by adaline** [comment] 2015-11-11 13:09
@izderadicka 
Hi Ivan,
I have updated the master branch to include the workaround, can you test it out for me please (works fine here as before!).

**Comment by izderadicka** [comment] 2015-11-11 16:18
Hi Valentin

unfortunatelly with this step added:

Step 4 : RUN dpkg-divert --local --rename --add /sbin/initctl && ln -s 
-f /bin/true /sbin/initctl
  ---> Running in 441aaafbabf6
Leaving 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
  ---> 602b3fb4929a


still got same error when building:

Processing triggers for dovecot-core (1:2.2.18-2ubuntu2) ...
  * Restarting IMAP/POP3 mail server dovecot
    ...done.
  * Starting IMAP/POP3 mail server dovecot
Fatal: Dovecot is already running with PID 3586 (read from 
/var/run/dovecot/master.pid)
    ...fail!
invoke-rc.d: initscript dovecot, action "start" failed.
dpkg: error processing package dovecot-core (--configure):
  subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
  dovecot-core
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c echo "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d 
&&     apt-get update && apt-get install -y     rsyslog     ssl-cert     
postfix dovecot-imapd &&     apt-get clean &&     rm -rf 
/var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 100


I.

**Comment by adaline** [comment] 2015-11-15 16:29
I have found and fixed the issue:

In `core`'s Dockerfile, before package install: `echo "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d`
changes the invoke policy for services, i have moved this line to be after the package install calls.

Also I have added a vagrant script, which lets you test build the images in a neutral environment.
Let me know if you have any more issues, i will finally close this one :)
Thanks for all your feedback guys :+1:

**Closed by adaline** 2015-11-15 16:29 UTC
